# Generated by Django 3.0.4 on 2020-03-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='images',
            field=models.FileField(blank=True, help_text='Browse the file here', upload_to='files'),
        ),
    ]
