# Generated by Django 3.0.4 on 2020-04-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200407_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='images',
            field=models.FileField(blank=True, help_text='Browse the file here It  accepts only csv files only', upload_to='files'),
        ),
    ]
