# Generated by Django 3.0.4 on 2020-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200407_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='images',
            field=models.FileField(blank=True, help_text='Browse the file here and insert only csv files only', upload_to='files'),
        ),
    ]
