# Generated by Django 3.0.4 on 2020-04-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200408_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='images',
            new_name='file',
        ),
    ]
