# Generated by Django 3.0.4 on 2020-04-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200408_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='file',
            new_name='images',
        ),
    ]
