# Generated by Django 3.0.4 on 2020-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200408_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='images',
            field=models.FileField(help_text='Browse the file here and insert only csv files only', upload_to='files'),
        ),
    ]
